"""アプリ定数。"""

from __future__ import annotations

APP_DIR_NAME = "StreamHeartbeat_Nu"
PORTABLE_DIRNAME = "data"
CHROMA_HEX = "#00FF00"
DEFAULT_BPM = 70
DEFAULT_BEAT_TEXT = "ドクン"
ARRHYTHMIA_TEXT = "不整脈！"
MISMATCH_BPM = 20
ARRYTHMIA_DEVIATION = 0.25
ARRHYTHMIA_STREAK = 2
ARRHYTHMIA_COOLDOWN_S = 8.0
LOST_INTERVALS = 2.5
MIN_BPM = 20
MAX_BPM = 220
INNER_MARGIN = 0.15
MAX_BURSTS = 3
MAX_RIPPLES = 4
RIPPLE_S = 0.55
RIPPLE_R0 = 0.10
RIPPLE_R1 = 0.42
TAP_GOAL = 4
BURST_FADE_IN_S = 0.25
BURST_HOLD_S = 0.2
BURST_FADE_OUT_S = 0.35
DISCLAIMER = "これは医療機器ではありません。診断・治療には使えません。"
DETECT_LOST_LABEL = "検出できていません"
LIVE_STATUS = "連動中"
PREVIEW_IDLE_STATUS = "プレビュー（心音なし）"
PREVIEW_LOST_STATUS = "プレビュー（検出ロスト）"
PREVIEW_MOTION = 0.42
