"""アプリ定数。"""

from __future__ import annotations

APP_DIR_NAME = "StreamHeartbeat_Nu"
PORTABLE_DIRNAME = "data"
CHROMA_HEX = "#00FF00"
DEFAULT_BPM = 70
DEFAULT_BEAT_TEXT = "❤"
DEFAULT_BEAT_TEXT_X = 0.50
DEFAULT_BEAT_TEXT_Y = 0.22
DEFAULT_BPM_X = 0.50
DEFAULT_BPM_Y = 0.88
DEFAULT_BPM_COLOR = "#FFFFFF"
DEFAULT_BPM_OUTLINE = "#000000"
DEFAULT_BEAT_TEXT_COLOR = "#FF4D4D"
DEFAULT_BEAT_TEXT_OUTLINE = "#000000"
DEFAULT_BEAT_TEXT_SCALE = 1.4
DEFAULT_BACKDROP = "green"
BEAT_TEXT_JITTER = 0.12
DEFAULT_BEAT_TEXT_TILT = 0.7
BEAT_TEXT_ANGLE_JITTER_DEG = 12.0
HEART_CENTER = (0.50, 0.50)
BACKDROP_COLORS = {
    "green": "#00FF00",
    "white": "#FFFFFF",
    "black": "#000000",
    "transparent": "#00000000",
}
ARRHYTHMIA_TEXT = "不整脈！"
MISMATCH_BPM = 20
ARRYTHMIA_DEVIATION = 0.25
ARRHYTHMIA_STREAK = 2
ARRHYTHMIA_COOLDOWN_S = 8.0
LOST_INTERVALS = 2.5
BPM_DISPLAY_S = 1.5
MIN_BPM = 20
MAX_BPM = 220
INNER_MARGIN = 0.15
MAX_BURSTS = 3
MAX_RIPPLES = 4
RIPPLE_S = 0.55
RIPPLE_R0 = 0.10
RIPPLE_R1 = 0.42
TAP_GOAL = 4
BURST_FADE_IN_S = 0.25
BURST_HOLD_S = 0.2
BURST_FADE_OUT_S = 0.35
DISCLAIMER = "これは医療機器ではありません。診断・治療には使えません。"
DETECT_LOST_LABEL = "検出できていません"
LIVE_STATUS = "心拍同期表示中"
PREVIEW_IDLE_STATUS = "プレビュー中（心音未認識）"
PREVIEW_LOST_STATUS = "プレビュー中（心音未認識）"
