"""アプリ定数。"""

from __future__ import annotations

APP_DIR_NAME = "StreamHeartbeat_Nu"
PORTABLE_DIRNAME = "data"
CHROMA_HEX = "#00FF00"
DEFAULT_BPM = 70
DEFAULT_BEAT_TEXT = "ドクン"
ARRHYTHMIA_TEXT = "不整脈！"
MISMATCH_BPM = 20
ARRYTHMIA_DEVIATION = 0.25
ARRHYTHMIA_STREAK = 2
ARRHYTHMIA_COOLDOWN_S = 8.0
LOST_INTERVALS = 2.5
MIN_BPM = 20
MAX_BPM = 220
INNER_MARGIN = 0.15
MAX_BURSTS = 3
BURST_FADE_IN_S = 0.25
BURST_HOLD_S = 0.2
BURST_FADE_OUT_S = 0.35
DISCLAIMER = "これは医療機器ではありません。診断・治療には使えません。"
DETECT_LOST_LABEL = "検出できていません"
